version: 0.2
phases: 
 pre_build:
    commands:
      #- echo "This is from first inside" > file2efs.txt
      - ls -ltr
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
