version: 0.2
phases: 
 pre_build:
    commands:
      #- echo "This is from first inside" > file2efs.txt
      - ls -ltr
artifacts:
  files:
    - '**/*'
  name: web-mapviewer/BUILD_TYPE_3/APP_VERSION

